services:
  postgres:
    image: 'postgres:latest'
    # Reinicios automaticos solo si el contenedor se apaga por error
    restart: unless-stopped
    environment:
      - 'POSTGRES_DB=confecciones_dym_bd'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata: